name: Update All

#on:
#  schedule:
#    - cron: '15 17 * * *'
jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Sostituisci 'x' con la tua versione di Python desiderata.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas tqdm colorama  

    - name: Update Nessus Plugin
      run: |
        # Esegue la richiesta GET per ottenere il codice utilizzato per lanciare i js della get lo stesso codice funziona anche per altre get.
        curl -S https://www.tenable.com/plugins/nessus/186284 | grep -o "/_next/static/[A-Za-z0-9]\+/_buildManifest.js" | sed -e 's#/_next/static/##' -e 's#/_buildManifest.js##' > plugin/nessus/keyforget.csv
        
        # Scarico i nuovi ID dei nuovi plugin.
        curl -S https://www.tenable.com/plugins/feeds?sort=newest | grep -o "<link>https://www.tenable.com/plugins/nessus/[0-9]\+</link>" | sed -n 's/.*\/\([0-9]*\)<\/link>.*/\1/p' > plugin/nessus/cleaned_numbers.csv
        
        python plugin/nessus/update.py
        python create_all_cve-light.py
        python createdictionary.py
    name: Commit Changes
      run: |
        git config --global user.name 'ZeMatt90'
        git add plugin/nessus/keyforget.csv plugin/nessus/cleaned_numbers.csv data/all_cve-light.csv data/dictionary.csv data/nessus-kb.csv # Aggiungi tutti i file che vuoi includere nel commit.
        git commit -m "Auto update nessus plugin and cve"
    name: Push Changes
      run: |
        #git remote add origin-with-creds https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git remote add origin-with-creds https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push origin-with-creds HEAD:${{ github.ref }}
        