name: Update All

on:
  schedule:
    - cron: '50 16 * * *'


jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas tqdm colorama  

    - name: Update Nessus Plugin
      run: |
        # Esegue la richiesta GET per ottenere il codice utilizzato per lanciare i js della get lo stesso codice funziona anche per altre get.
        curl -S https://www.tenable.com/plugins/nessus/186284 | grep -o "/_next/static/[A-Za-z0-9]\+/_buildManifest.js" | sed -e 's#/_next/static/##' -e 's#/_buildManifest.js##' > plugin/nessus/keyforget.csv
        
        # Scarico i nuovi ID dei nuovi plugin.
        curl -S https://www.tenable.com/plugins/feeds?sort=newest | grep -o "<link>https://www.tenable.com/plugins/nessus/[0-9]\+</link>" | sed -n 's/.*\/\([0-9]*\)<\/link>.*/\1/p' > plugin/nessus/cleaned_numbers.csv
        
        python plugin/nessus/update.py
        python create_all_cve-light.py
        python createdictionary.py
    
    - name: Commit & Push Changes
      run: |
        git config --global user.name 'ZeMatt90'
        git config --global user.email 'zenit90+git@gmail.com'
        git add plugin/nessus/keyforget.csv plugin/nessus/cleaned_numbers.csv data/all_cve-light.csv data/dictionary.csv data/nessus-kb.csv 
        git commit -m "Auto update nessus plugin and cve"
        if git push; then
          echo "Operazione completata con successo"
        else
          echo "Errore durante l'operazione, verifica il log per ulteriori dettagli"
          exit 1  
        fi

